### ISSUE TITLE
Bookdown question

### ISSUE THREAD

**Issue by apreshill** [rstudio-education/arm-workshop-rsc2019#11]
Hi @yihui,

One thing I have run into pulling together teaching materials for bookdown is that if my book won't render, I end up with all the intermediate files in my root project directory. Is there a way to direct those files into a folder just in case of failure to render? It makes it hard to clean up your project directory if the book fails to render. An example for me was trying to work with Jenny's [Happy Git with R book](https://github.com/jennybc/happy-git-with-r)- I had to edit one chapter to make the book render, but then I had to manually delete all the intermediate files that cluttered up my project directory. I searched GitHub issues and the documentation and have asked around- no one has any ideas!

Thanks-
Alison

**Comment by yihui** [comment]
What kind of intermediate files did you see? Like `*.utf8.md`? These files should be automatically cleaned up once the book can be successfully rendered.

`new_session: true` will generate more intermediate files than the default `new_session: false`: https://github.com/jennybc/happy-git-with-r/blob/master/_bookdown.yml#L6

**Comment by apreshill** [comment]
Ah good to know! Yes all the `.md` files were there- I assumed it cleaned up the old files in the output directory, but didn't realize those in the project root would also get cleaned up.
