### ISSUE TITLE
Memor removed from CRAN

### ISSUE THREAD

**Issue by apreshill** [rstudio-education/arm-workshop-rsc2019#21]
https://cran.r-project.org/web/packages/memor/index.html

They couldn't install memor on the cloud setup because it was removed from CRAN. Do you have a backup plan?

**Comment by haozhu233** [comment]
I changed the installation to github <https://github.com/rstudio-education/arm-workshop-rsc2019/commit/a3734365c375d5906091f2e779e5dedd640d2a9d> and I will do an announcement about this before the session starts.

**Comment by haozhu233** [comment]
I also submitted memor back to CRAN last night and now it's back on. Cheer for Uwe!!
