### ISSUE TITLE
knitr::include_graphics() may not be the best way to control image size in xarnigan

### ISSUE THREAD

**Issue by skolenik** [rstudio-education/arm-workshop-rsc2019#25]
The slide `All other images` proposes to use `include_graphics()` to control the image size. I was not able to make it work (probably because it is supposed to interact with Pandoc, and `xarnigan` skips that). I had better luck with `out.width` chunk option.

**Comment by apreshill** [comment]
Yes, thank you for noting this, adding slide link here:
http://arm.rbind.io/slides/xaringan.html#otherimages
