### ISSUE TITLE
Use YAML instead of TOML?

### ISSUE THREAD

**Issue by yihui** [rstudio-education/arm-workshop-rsc2019#4]
Because blogdown only supports YAML for R Markdown: https://bookdown.org/yihui/blogdown/configuration.html TOML works, but the downside is that blogdown's timestamp-based caching won't work (i.e. if output file is newer, the source file won't be recompiled each time).

When creating new posts, you can use the "New Post" addin, which will always generate YAML for you.  You may also need to choose the appropriate archetype from the addin, and this may require `remotes::install_github('rstudio/blogdown')` (https://github.com/rstudio/blogdown/issues/350).

**Comment by apreshill** [comment]
This is really helpful- thank you! I see the archetypes now in the dropdown for the docs I am using, will clean this up!

**Comment by apreshill** [comment]
Hmm I get this error:

```
> blogdown:::new_post_addin()

Listening on http://127.0.0.1:7556
/Users/alison/rprojs/arm-workshop-rsc2019/content/prework/test.md created
Warning in file(con, "r") :
  cannot open file 'content/content/prework/test.md': No such file or directory
Warning: Error in file: cannot open the connection
  90: file
  89: readLines
  86: hugo_toYAML
  85: new_content
  84: blogdown::new_post
  83: observeEventHandler
  12: shiny::runApp
  11: shiny::runGadget
  10: eval
   9: eval
   4: eval
   3: eval
   2: sys.source
   1: blogdown:::new_post_addin
```

When I select `.Rmarkdown` as the file type (which I need to do in order to have the TOC render on the right). It ends up creating just a plain old `.md` file with TOML instead of YAML.

**Comment by apreshill** [comment]
ah I just figured out it is a working directory problem- I didn't realize the addin went relative to the dir I am in.

**Comment by yihui** [comment]
The working directory issue has been fixed in the dev version of **blogdown**. The working directory no longer has to be the root directory of the website.
