### ISSUE TITLE
Blogdown: new_site directory structure has changed?

### ISSUE THREAD

**Issue by apreshill** [rstudio-education/arm-workshop-rsc2019#8]
Hi @yihui,

In prepping for the blogdown part of this workshop, I noticed that all my old teaching materials are wrong 😭 Previously when I built a new blogdown site, I would see something [like](https://gohugo.io/getting-started/directory-structure/):
```
.
├── archetypes
├── assets
├── config.toml
├── content
├── data
├── layouts
├── static
└── themes
```
Here are some screenshots:
+ [lithium theme](https://apreshill.github.io/blogdown-workshop/slides/blogdown-workshop-slides.html#24)
+ [cocoa eh theme](https://apreshill.github.io/data-vis-labs-2018/slides/06-slides_blogdown.html#13). 

Looks like [Emily Zabor saw the same thing](https://www.emilyzabor.com/tutorials/rmarkdown_websites_tutorial.html#blogs). 

Now I am getting:
<img width="471" alt="screen shot 2018-12-28 at 8 05 36 pm" src="https://user-images.githubusercontent.com/12160301/50533311-fbcad380-0adb-11e9-9108-84d262d4ebfd.png">

So the empty `archetypes`, `layouts`, and `data` folders are missing.

Did something change with the package? I am using the development version from GitHub, and went through the recent commits and don't really see any intentional wiping out of these empty directories. I'm wondering if there is something about my system set-up that is causing this, or is it intentional behavior?

Thanks!
Alison

**Comment by apreshill** [comment]
Ah I saw that commit but thought it was just cleaning out the resources folder! I actually like the empty directory structure provided before, because it gave the shell for people to do the right thing- override the theme files rather than edit them. So my vote is to keep them so that the barebones structure is consistent with the [Hugo directory structure docs](https://gohugo.io/getting-started/directory-structure/) as much as possible.

**Comment by apreshill** [comment]
Thinking more about this, what about an argument to the `new_site` function like `dir_structure` that defaults to FULL, but has an argument for MINIMAL, which wipes out empty folders? In my search for answers, I was looking through the function documentation for an argument I was missing.

**Comment by yihui** [comment]
Sounds like a good idea. I'll add an argument, and perhaps preserve the empty dirs by default.

**Comment by apreshill** [comment]
@yihui can you confirm- for the workshop we'll leave as is, and I'll teach participants to add those empty directories in their projects? I can say that in a future dev version those empty dirs may return?

**Comment by yihui** [comment]
With the dev version of **blogdown**, they can choose whether to preserve or delete the empty dirs via `new_site(empty_dirs = TRUE/FALSE)`, or the RStudio project wizard:

![image](https://user-images.githubusercontent.com/163582/50659644-e4b83580-0f62-11e9-9838-4a81483bf3a5.png)

**Comment by yihui** [comment]
FYI I have released a new version of **blogdown** to CRAN (binaries should be available in one day or two).
