### ISSUE TITLE
Blogdown: exampleSite content with TOML?

### ISSUE THREAD

**Issue by apreshill** [rstudio-education/arm-workshop-rsc2019#9]
Hi @yihui (sorry for all the questions on a Friday night!),

One other thing I am noticing with different themes is that the example site content TOML is often left in place and not converted to YAML. That is how I ended up with TOML still in the workshop site using the academic theme docs, but you can see here with the future imperfect theme (which I was planning to use for the workshop):
https://github.com/apreshill/ada-blog/tree/hugo-theme-future-imperfect/content

I have tried different themes in different branches so you can see how hit-and-miss it is.

**Comment by yihui** [comment]
Good point. Perhaps I should run `hugo_convert()` in `new_site()` by default.

**Comment by apreshill** [comment]
@yihui also to confirm, for the workshop, to convert to YAML the `exampleSite` files within the project root directory produced by using:

```
new_site(theme = "jpescador/hugo-future-imperfect", theme_example = TRUE, sample = TRUE)
```

I should encourage our participants to run:

```
> hugo_convert(to = "YAML", unsafe = TRUE)
processing 27 content files
```

It *looks* like this didn't touch my intentional TOML files like config.toml and netlify.toml. Would you recommend this workflow?

**Comment by yihui** [comment]
In the current dev version of **blogdown**, I have done the conversion to YAML by default.

`*.toml` files won't be touched (by [`hugo convert toYAML`](https://gohugo.io/commands/hugo_convert/)), though.
